### ISSUE TITLE
Bug - A Node.js API is used (process.hrtime) which is not supported in the Edge Runtime.

### ISSUE THREAD

**Issue by ttavni** [sanity-io/sanity-template-nextjs-app-router-personal-website#76]
I followed the setup instructions with a fresh environment. It does not block anything but I'm getting

```
- error Error: A Node.js API is used (process.hrtime) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime
    at __webpack_require__ (/.next/server/edge-runtime-webpack.js:37:33)
    at fn /.next/server/edge-runtime-webpack.js:310:21)
    at __webpack_require__ (/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/next/server/edge-runtime-webpack.js:310:21)
    at __webpack_require__ (/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/.next/server/edge-runtime-webpack.js:310:21)
    at __webpack_require__ (/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/.next/server/edge-runtime-webpack.js:310:21)
    at eval (./app/studio/[[...index]]/Studio.tsx:6:76)
    at (ssr)/./app/studio/[[...index]]/Studio.tsx (/.next/server/app/studio/[[...index]]/page.js:5903:1)
    at __webpack_require__ (/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/.next/server/edge-runtime-webpack.js:310:21)
````

**Comment by stipsan** [comment]
Could you share the exact steps you ran to reproduce this? Not seeing it on our end 😅

**Comment by stipsan** [comment]
Should be fixed by https://github.com/sanity-io/sanity-template-nextjs-app-router-personal-website/commit/3c22160dfa39ca8417eb79195207b154638f1851
